### ISSUE TITLE
/type页面打不开

### ISSUE THREAD

**Issue by Royage888** [laowenruo/Spring-Blog#1]
<img width="746" alt="截屏2021-07-07 上午9 23 17" src="https://user-images.githubusercontent.com/56480821/124686044-f8aeca80-df04-11eb-9c14-65dedf2df0d9.png">

<img width="1110" alt="截屏2021-07-07 上午9 25 06" src="https://user-images.githubusercontent.com/56480821/124686219-44617400-df05-11eb-915c-e7d06c98d4ab.png">

**Comment by laowenruo** [comment]
缓存操作，看看redis配置填了吗？
