### ISSUE TITLE
图片无法加载

### ISSUE THREAD

**Issue by Royage888** [laowenruo/Spring-Blog#2]
<img width="783" alt="截屏2021-07-07 上午9 53 20" src="https://user-images.githubusercontent.com/56480821/124688335-2ac22b80-df09-11eb-8478-8509a3e60758.png">

**Comment by Royage888** [comment]
<img width="501" alt="截屏2021-07-07 上午9 54 07" src="https://user-images.githubusercontent.com/56480821/124688401-462d3680-df09-11eb-8292-77ee54addc84.png">

**Comment by laowenruo** [comment]
图片采用CDN，部分CDN图床失效，正在升级为对象OSS存储
