### ISSUE TITLE
主页经常加载中断,显示这个问题

### ISSUE THREAD

**Issue by Royage888** [laowenruo/Spring-Blog#3]
![9F2AF9BC694EF42A19D5D867094D11A0](https://user-images.githubusercontent.com/56480821/124690023-2ea37d00-df0c-11eb-95d3-5ee75ce17c0e.png)

**Comment by Royage888** [comment]
![4520F20B420D271F1304C5F4521813FC](https://user-images.githubusercontent.com/56480821/124690251-7cb88080-df0c-11eb-8d4b-42a5e8730172.jpg)

**Comment by Royage888** [comment]
Mac与window机型都出现这种问题,时有时无

**Comment by laowenruo** [comment]
今天晚上新增一些功能，然后看看
