### ISSUE TITLE
idea可以正常运行,部署无法访问

### ISSUE THREAD

**Issue by 1412849797** [laowenruo/Spring-Blog#6]
你好，我下的是之前的版本
在idea启动所有的功能都是正常的，
使用maven打包后，用java -jar 运行，后台可以正常使用，但是前端页面全都无法访问

**Comment by laowenruo** [comment]
你好，前端提示什么呢？后端数据库有内容吗？

**Comment by 1412849797** [comment]
后端所有功能都正常，前端是空白页面，页面的标题显示500错误，
日志显示是thymeleaf解析错误

**Comment by laowenruo** [comment]
应该是你的数据库没有内容，你随意生成几条数据看看

**Comment by 1412849797** [comment]
第一张是idea运行的，剩下两张是打包后运行的，我尝试添加了几个文章进去后还是一样
![image](https://user-images.githubusercontent.com/59927567/159021500-bb1eeca8-dc60-40b9-ba82-8045727a3126.png)
![image](https://user-images.githubusercontent.com/59927567/159021601-915b7ee1-d208-4543-9ef5-47f19731f7bc.png)
![image](https://user-images.githubusercontent.com/59927567/159021709-d29f6933-3ae7-443f-983f-ee210a9bd5a9.png)

**Comment by laowenruo** [comment]
加我QQ 1173779946 帮你看看

**Comment by laowenruo** [comment]
ok
